SuccessGetMeResponse:
  type: object
  properties:
    id:
      type: string
      example: "123"
      description: User ID
    name:
      type: string
      example: "John Doe"
      description: User's full name
    email:
      type: string
      format: email
      example: "john@example.com"
      description: User's email address

UnauthorizedGetMeResponse:
  type: object
  properties:
    error:
      type: string
      example: Unauthorized
      description: Error message

InternalErrorGetMeResponse:
  type: object
  properties:
    error:
      type: string
      example: Internal server error
      description: Error message
