openapi: 3.1.0

info:
  title: Backend Framework API
  description: OpenAPI Swagger Docs
  version: 1.0.1
  license:
    name: MIT
    identifier: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: /api/v1
    description: API v1

tags:
  - name: Status
    description: API Status
  - name: Auth
    description: Auth

components:
  securitySchemes:

    BearerAuth:
      type: http
      scheme: bearer

  schemas:
    $ref: schemas.yaml

paths:
  $ref: paths/path.yaml
